version: "3.8"
services:
  scoring:
    build: .
    volumes:
      - ./models:/app/models
      - ./src:/app
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/iforest_model_v1.pkl

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
    volumes:
      - ./n8n:/home/node/.n8n
