version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - n8n_network

  python_scoring:
    build:
      context: ./python_scoring
    container_name: python_scoring
    restart: always
    environment:
      MODEL_PATH: /app/models/ensemble_model_v1.pkl
      MODEL_VERSION: v1
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: DB_PASSWORD
      DB_DATABASE: n8n_workflows
      SCORE_THRESHOLD_HIGH: -0.3
      SCORE_THRESHOLD_MED: -0.1
    ports:
      - "8000:8000"
    volumes:
      - ./python_scoring/models:/app/models
    depends_on:
      - mysql
    networks:
      - n8n_network

  n8n:
    image: n8nio/n8n:1.119.1
    container_name: n8n
    restart: always
    environment:
      DB_TYPE: mysqldb
      DB_MYSQLDB_HOST: mysql
      DB_MYSQLDB_PORT: 3306
      DB_MYSQLDB_DATABASE: n8n_workflows
      DB_MYSQLDB_USER: root
      DB_MYSQLDB_PASSWORD: DB_MYSQLDB_PASSWORD
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - python_scoring
      - mysql
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge
